# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000
#  username: postgres
#  host: postgres

#development:
#  <<: *default
#  database: my_database_development

#test:
#  <<: *default
#  database: my_database_test

#production:
#  <<: *default
#  database: my_database_production

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: fullstack-challenge

test:
  <<: *default
  database: testdb

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>


#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: 5


#development:
#  <<: *default
#  database: database_name
#  username: liubomyr
#  password: '—-'

#test:
#  <<: *default
#  database: database_name
#  username: liubomyr
#  password: '—-'

#production:
#  <<: *default
#  database: database_name
#  username: liubomyr
#  password: '—-'




#development:
#  adapter: postgresql
#  database: my_database_development
#  pool: 5
#  timeout: 5000

#test:
#  adapter: postgresql
#  database: my_database_test
#  pool: 5
#  timeout: 5000

#production:
#  adapter: postgresql
#  database: my_database_production
#  pool: 5
#  timeout: 5000